security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    App\Entity\User: "auto"
  enable_authenticator_manager: true
  providers:
    users:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
    api:
      pattern: ^/api/
      stateless: true
      provider: users
      json_login:
        check_path: auth # The name in routes.yaml is enough for mapping
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~

  role_hierarchy:
    ROLE_PLAYER: ROLE_USER
    ROLE_GAME_MASTER: [ROLE_PLAYER]
    ROLE_ADMIN: [ROLE_GAME_MASTER]

  access_control:
    - {
        path: ^/api/users,
        roles: ROLE_ADMIN,
        methods: [GET, PUT, PATCH, DELETE],
      }
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
